"""authors model

Revision ID: 52191d70e3c3
Revises: 7e55e0648a84
Create Date: 2023-05-03 20:41:40.505558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52191d70e3c3'
down_revision = '7e55e0648a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    op.drop_table('author')
    # ### end Alembic commands ###
