"""pass and first and last in user model

Revision ID: 7e55e0648a84
Revises: 7ea165988aa4
Create Date: 2023-05-01 02:39:11.743984

"""
from alembic import op
import sqlalchemy as sa
from blog.models import User
from blog.models.datebase import db
from werkzeug.security import generate_password_hash


# revision identifiers, used by Alembic.
revision = '7e55e0648a84'
down_revision = '7ea165988aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), server_default='', nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), server_default='', nullable=False))
        sa.UniqueConstraint('_password')

    # ### end Alembic commands ###
    admin = User.query.filter_by(username='admin').one_or_none()
    admin.email = 'admin@admin.ru'
    admin.password = '1'
    db.session.commit()

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('_password')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
